### ISSUE TITLE
Map vs Arrays?

### ISSUE THREAD

**Issue by cyrusmsk** [jinyus/dirsplitter#1]
Hi there.
Nice small project. I've checked several implementations (and ported btw the code to D) and found out that some implementations are using regular arrays while the others are using dict/map structures.
Did you compare them? Which one is more suitable for the tool?

**Comment by zupat** [comment]
I'm not sure what functionality you're referring to, but a map is needed for the tracker.

**Comment by cyrusmsk** [comment]
For FolderToDelete in Reverse function. Nim and Crystal are using arrays, Go and Python are kind of set

**Comment by zupat** [comment]
Though it's rarely needed, using a set makes it more resilient so the versions that uses an array should be updated.

Case where using an array would cause an issue:

When you had a folder named "partx" in your original folder. So the splitted folder would yield "partx/partx", if it deletes the parent first, when it gets to the subfolder, it will fail because it wouldn't exist.

Another way to bulletproof it would be to only add top-level part folders, then it'd be safe to use an array.

**Comment by cyrusmsk** [comment]
Thanks. In D in reverse function - I've changed the logic a bit, so only first level of hierarchy is searched for 'partX' folders. I think it should work even faster.
